ALTER TABLE `magic_videos`
  ADD COLUMN `original_filename` VARCHAR(255) NOT NULL DEFAULT '' AFTER `file_path`,
  ADD COLUMN `stored_filename` VARCHAR(255) NOT NULL DEFAULT '' AFTER `original_filename`,
  ADD COLUMN `storage_type` VARCHAR(32) NOT NULL DEFAULT 'local' AFTER `stored_filename`,
  ADD COLUMN `oss_bucket` VARCHAR(255) NOT NULL DEFAULT '' AFTER `storage_type`,
  ADD COLUMN `oss_endpoint` VARCHAR(255) NOT NULL DEFAULT '' AFTER `oss_bucket`,
  ADD COLUMN `oss_object_key` VARCHAR(1024) NOT NULL DEFAULT '' AFTER `oss_endpoint`,
  ADD COLUMN `oss_url` VARCHAR(2048) NOT NULL DEFAULT '' AFTER `oss_object_key`,
  ADD COLUMN `cdn_url` VARCHAR(2048) NOT NULL DEFAULT '' AFTER `oss_url`,
  ADD COLUMN `play_url` VARCHAR(2048) NOT NULL DEFAULT '' AFTER `cdn_url`,
  ADD COLUMN `hls_url` VARCHAR(2048) NULL DEFAULT NULL AFTER `play_url`,
  ADD COLUMN `cover_url` VARCHAR(2048) NULL DEFAULT NULL AFTER `hls_url`,
  ADD COLUMN `duration` INT NOT NULL DEFAULT 0 AFTER `duration_seconds`,
  ADD COLUMN `upload_status` VARCHAR(16) NOT NULL DEFAULT 'completed' AFTER `status`,
  ADD COLUMN `upload_error` TEXT NULL AFTER `upload_status`,
  ADD COLUMN `transcode_status` VARCHAR(16) NOT NULL DEFAULT 'none' AFTER `upload_error`,
  ADD COLUMN `deleted_at` DATETIME NULL DEFAULT NULL AFTER `updated_at`;
