SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `magic_audio_makeup_settings` (
  `id`           BIGINT     NOT NULL AUTO_INCREMENT,
  `enabled`      TINYINT(1) NOT NULL DEFAULT 0,
  `make_up_days` INT        NOT NULL DEFAULT 0,
  `updated_by`   BIGINT     NULL DEFAULT NULL,
  `created_at`   DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`   DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='读书打卡补卡设置';
