import AdminAudioStatsPanel from "./AdminAudioStatsPanel";
import AdminAudioTranscribePanel from "./AdminAudioTranscribePanel";
import useReadingSeriesAdmin from "./useReadingSeriesAdmin";

export function useAdminReadingTabItems({
  readingAdminState,
  readingAdminActions,
  readingAdminDeps,
}) {
  const {
    readingContentMonth,
    readingContentKeyword,
    readingContentPage,
    readingContentPageSize,
    readingContentSeriesId,
    readingContentSeriesFilterRows,
    readingContents,
    readingContentsTotal,
    selectedReadingContentRowKeys,
    readingPushSummaryMap,
    retryingReadingContentId,
    readingImportSubmitting,
    audioMakeupSetting,
    audioMonth,
    audioDateRange,
    audioReadingContentId,
    audioDepartment,
    audioUserId,
    audioStatusFilter,
    audioReadingOptions,
    audioLegacyHint,
    audioReadingStatsRows,
    users,
  } = readingAdminState;

  const {
    setReadingContentMonth,
    setReadingContentKeyword,
    setReadingContentPage,
    setReadingContentPageSize,
    setReadingContentSeriesId,
    setSelectedReadingContentRowKeys,
    handlePreviewReadingImport,
    openReadingImportMaterialPicker,
    openCreateReadingContentModal,
    openEditReadingContentModal,
    handleToggleReadingContentStatus,
    handleDeleteReadingContent,
    handleBatchDeleteReadingContents,
    handleBatchEnableReadingContents,
    handleBatchDisableReadingContents,
    handleOpenReadingPushDetail,
    handleRetryReadingPush,
    onReadingSeriesChanged,
    setAudioMakeupSetting,
    handleSaveAudioMakeupSetting,
    setAudioMonth,
    setAudioDateRange,
    setAudioReadingContentId,
    setAudioDepartment,
    setAudioUserId,
    setAudioStatusFilter,
    reloadAdminReadingAudioStats,
    handleOpenAudioExportModal,
    openAudioDetail,
  } = readingAdminActions;

  const { downloadMagicFile, buildReadingAdminTabItems, message, RangePicker, superAdminMode } = readingAdminDeps;
  const {
    readingSeriesRows,
    readingSeriesSelectRows,
    readingSeriesModal,
    setReadingSeriesModal,
    readingSeriesKeyword,
    setReadingSeriesKeyword,
    readingSeriesPage,
    setReadingSeriesPage,
    readingSeriesTotal,
    readingSeriesStatus,
    setReadingSeriesStatus,
    readingSeriesSubmitting,
    setReadingSeriesRefreshKey,
    readingSeriesDetailOpen,
    setReadingSeriesDetailOpen,
    readingSeriesDetailLoading,
    setReadingSeriesDetailLoading,
    readingSeriesDetail,
    setReadingSeriesDetail,
    reloadReadingSeriesSelectOptions,
    openReadingSeriesModal,
    closeReadingSeriesModal,
    handleSubmitReadingSeries,
    openReadingSeriesDetail,
    handleToggleReadingSeriesStatus,
    handleArchiveReadingSeries,
  } = useReadingSeriesAdmin({
    enabled: readingAdminDeps.shouldLoadReadingSeries,
    optionsEnabled: readingAdminDeps.readingSeriesOptionsEnabled,
    readingSeriesForm: readingAdminDeps.readingSeriesForm,
    reloadReadingContentSeriesFilterOptions: readingAdminDeps.reloadReadingContentSeriesFilterOptions,
    setReadingContentPreferredSeriesId: readingAdminDeps.setReadingContentPreferredSeriesId,
    message,
    showLoadError: readingAdminDeps.showLoadError,
    onSeriesChanged: onReadingSeriesChanged,
  });

  return {
    readingSeriesSupport: {
      readingSeriesSelectRows,
      readingSeriesModal,
      setReadingSeriesModal,
      openReadingSeriesModal,
      closeReadingSeriesModal,
      readingSeriesSubmitting,
      handleSubmitReadingSeries,
      setReadingSeriesRefreshKey,
      readingSeriesDetailOpen,
      setReadingSeriesDetailOpen,
      readingSeriesDetailLoading,
      setReadingSeriesDetailLoading,
      readingSeriesDetail,
      setReadingSeriesDetail,
      reloadReadingSeriesSelectOptions,
      openReadingSeriesDetail,
    },
    tabItems: [
      ...buildReadingAdminTabItems({
        readingContentMonth,
        setReadingContentMonth,
        readingContentKeyword,
        setReadingContentKeyword,
        setReadingContentPage,
        readingContentPageSize,
        setReadingContentPageSize,
        readingContentSeriesId,
        setReadingContentSeriesId,
        readingContentSeriesFilterRows,
        downloadMagicFile,
        handlePreviewReadingImport,
        openReadingImportMaterialPicker,
        readingImportSubmitting,
        openCreateReadingContentModal,
        readingContents,
        readingContentPage,
        readingContentsTotal,
        selectedReadingContentRowKeys,
        setSelectedReadingContentRowKeys,
        openEditReadingContentModal,
        handleToggleReadingContentStatus,
        handleDeleteReadingContent,
        handleBatchDeleteReadingContents,
        handleBatchEnableReadingContents,
        handleBatchDisableReadingContents,
        readingPushSummaryMap,
        handleOpenReadingPushDetail,
        handleRetryReadingPush,
        retryingReadingContentId,
        readingSeriesRows,
        readingSeriesKeyword,
        setReadingSeriesKeyword,
        readingSeriesPage,
        setReadingSeriesPage,
        readingSeriesTotal,
        readingSeriesStatus,
        setReadingSeriesStatus,
        openReadingSeriesModal,
        openReadingSeriesDetail,
        handleToggleReadingSeriesStatus,
        handleArchiveReadingSeries,
      }),
      {
        key: "audio_stats",
        label: "打卡统计",
        children: (
          <AdminAudioStatsPanel
            audioStatsState={{
              audioMakeupSetting,
              audioMonth,
              audioDateRange,
              audioReadingContentId,
              audioDepartment,
              audioUserId,
              audioStatusFilter,
              audioReadingOptions,
              audioLegacyHint,
              audioReadingStatsRows,
              users,
            }}
            audioStatsActions={{
              setAudioMakeupSetting,
              handleSaveAudioMakeupSetting,
              setAudioMonth,
              setAudioDateRange,
              setAudioReadingContentId,
              setAudioDepartment,
              setAudioUserId,
              setAudioStatusFilter,
              reloadAdminReadingAudioStats,
              handleOpenAudioExportModal,
              openAudioDetail,
            }}
            audioStatsDeps={{
              RangePicker,
              message,
            }}
          />
        ),
      },
      ...(superAdminMode ? [{
        key: "audio_transcribe",
        label: "录音转写",
        children: <AdminAudioTranscribePanel users={users} />,
      }] : []),
    ],
  };
}
